# Generated by Django 3.2.16 on 2023-10-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='messages',
            field=models.CharField(default='Your default value here', max_length=255),
        ),
    ]
