# Generated by Django 3.2.16 on 2023-10-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='updated',
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
