# Generated by Django 3.2.16 on 2023-11-06 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_auto_20231106_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='participants',
            field=models.ManyToManyField(related_name='companies_participated_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
