# Generated by Django 3.2.16 on 2023-12-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCommercial',
            fields=[
                ('Jid', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('talents', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('companies', models.ManyToManyField(blank=True, related_name='commercials_companies', to='projects.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='commercials',
            field=models.ManyToManyField(blank=True, related_name='companies_commercials', to='projects.JobCommercial'),
        ),
    ]
